#IaC con docker compose per far girare mariadb, si puo adattare a seconda dei bisogni 
version: "3.9"
services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: gold
      MYSQL_DATABASE: dungeon
      MYSQL_USER: goblin
      MYSQL_PASSWORD: treasure
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
